version: '3.8'
services:
  uapi-db:
    image: postgres:14-alpine
    container_name: uapi_db_container
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=uapi-db
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

  uapi-service:
    build: ./uapi-service/uapi-service-server
    image: uapi-service
    container_name: uapi_service_container
    ports:
      - "9090:9090"
    depends_on:
      - uapi-db
    environment:
      - DB_HOST=uapi-db
      - DB_PORT=5432
      - DB_NAME=uapi-db
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

  uapi-gateway:
    build: ./uapi-gateway/
    image: uapi-gateway
    container_name: uapi_gateway_container
    ports:
      - "8080:8080"
    depends_on:
      - uapi-service
    environment:
      - UAPI_SERVICE_URL=http://uapi-service:9090