-- таблица users (с пользователями):
create TABLE IF NOT EXISTS users(
    user_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    first_name varchar(50) NOT NULL,
    last_name varchar(50),
    patronymic varchar(50),
    birthday date,
    email varchar(254) NOT NULL,
    phone varchar(20),
    password varchar(50) NOT NULL,
    registration_date timestamp NOT NULL,
    CONSTRAINT pk_user PRIMARY KEY (user_id),
    CONSTRAINT uq_user_email UNIQUE (email)
);

-- таблица roles (с ролями пользователей):
create TABLE IF NOT EXISTS roles(
    role_id integer GENERATED BY DEFAULT AS IDENTITY,
    name varchar(20) NOT NULL,
    CONSTRAINT pk_role PRIMARY KEY (role_id),
    CONSTRAINT uq_role_name UNIQUE (name)
);

-- таблица user_roles (связывает users и roles):
create TABLE IF NOT EXISTS user_roles(
    user_id BIGINT NOT NULL,
    role_id integer NOT NULL,
    CONSTRAINT uq_user_role UNIQUE (user_id, role_id),
    CONSTRAINT fk_user_roles_to_users FOREIGN KEY (user_id) REFERENCES users(user_id)
    ON delete CASCADE ON update CASCADE,
    CONSTRAINT fk_user_roles_to_roles FOREIGN KEY (role_id) REFERENCES roles(role_id)
    ON delete CASCADE ON update CASCADE
);